POST http://localhost:3333/checkins HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2MzMzMTI3LCJleHAiOjE2MTY5Mzc5Mjd9.hGV50y7o3WbcW5RXWKmAEhjZdVdc0nMtRU0OaHVvbEU

{
  "student_id" : 1
}

### 
GET http://localhost:3333/students/1/checkins HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2MzMzMTI3LCJleHAiOjE2MTY5Mzc5Mjd9.hGV50y7o3WbcW5RXWKmAEhjZdVdc0nMtRU0OaHVvbEU