POST http://localhost:3333/matricula HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1NzIzMjkyLCJleHAiOjE2MTYzMjgwOTJ9.TZXvGN2I5j25bzQaCDOg18UlPfmxELBFTkvf-jP-sYQ

{
  "start_date" : "2021-03-16T22:00:00+01:00",
  "student_id" : 1,
  "plan_id" : 2
}

###
GET http://localhost:3333/matricula HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1NzIzMjkyLCJleHAiOjE2MTYzMjgwOTJ9.TZXvGN2I5j25bzQaCDOg18UlPfmxELBFTkvf-jP-sYQ

###
PUT http://localhost:3333/matricula/1 HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1NzIzMjkyLCJleHAiOjE2MTYzMjgwOTJ9.TZXvGN2I5j25bzQaCDOg18UlPfmxELBFTkvf-jP-sYQ

{
  "start_date" : "2021-03-03T20:00:00+01:00"
}
