POST http://localhost:3333/students HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1OTI3MzcwLCJleHAiOjE2MTY1MzIxNzB9.4jIE7KL-bn45CGXDML7HJOHxQQmUIAOP_cfbwCz-OQE

{
  "name" : "Hamilton Silva",
  "email" : "test@gmail.com",
  "idade" : 19,
  "peso" : 62.2,
  "altura" : 72.9
  }

###

GET http://localhost:3333/students HTTP/1.1
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1OTI3MzcwLCJleHAiOjE2MTY1MzIxNzB9.4jIE7KL-bn45CGXDML7HJOHxQQmUIAOP_cfbwCz-OQE