// Criando varivel global 
@var = http://localhost:3333
// Criate appointement 
###
POST {{var}}/appointments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjE0MzM0NjgzLCJleHAiOjE2MTQ5Mzk0ODN9.LknhjhNWE8VC1H4vv4Ekl73L5LjL66Nwo_Nnsfv61uQ

{
  "provider_id" : 1,
  "date" : "2021-02-26T20:00:00+01:00"
}

###
GET {{var}}/appointments?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0MzYwNjQ1LCJleHAiOjE2MTQ5NjU0NDV9.0Vt45Xp8MAPjPVz8jXoeqxghXakVBV8dH7HpO0XUvJQ

### 
DELETE {{var}}/appointments/11 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjE0MzM0NjgzLCJleHAiOjE2MTQ5Mzk0ODN9.LknhjhNWE8VC1H4vv4Ekl73L5LjL66Nwo_Nnsfv61uQ
