// Criando varivel global 
@var = http://localhost:3333
// Criate appointement 
###
POST {{var}}/appointments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzODM1MjYxLCJleHAiOjE2MjQ0NDAwNjF9.NRDOeC2Y1pkp_Ae5WnUT-Xp0DL3qmPOxXH9O64JFZ00

{
  "provider_id" : 2,
  "date" : "2021-06-26T20:00:00+01:00"
}

###
GET {{var}}/appointments?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzODM1MjYxLCJleHAiOjE2MjQ0NDAwNjF9.NRDOeC2Y1pkp_Ae5WnUT-Xp0DL3qmPOxXH9O64JFZ00

### 
DELETE {{var}}/appointments/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzODM1MjYxLCJleHAiOjE2MjQ0NDAwNjF9.NRDOeC2Y1pkp_Ae5WnUT-Xp0DL3qmPOxXH9O64JFZ00
