// Criando varivel global 
@var = http://localhost:3333
###
GET {{var}}/notification HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0MzYwNjQ1LCJleHAiOjE2MTQ5NjU0NDV9.0Vt45Xp8MAPjPVz8jXoeqxghXakVBV8dH7HpO0XUvJQ

### 

// Ler uma notification 

### 
PUT {{var}}/notification/60392dc8200dbb10e8d6a0a4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0MzYwNjQ1LCJleHAiOjE2MTQ5NjU0NDV9.0Vt45Xp8MAPjPVz8jXoeqxghXakVBV8dH7HpO0XUvJQ

