# Criando session user normal
// É necessario mandar email and password 
@var = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzODM0NzIzLCJleHAiOjE2MjQ0Mzk1MjN9.Iel9KdnGUVjVE9pK1N2O_9FFnmpuV5XoUjdHfr4W7q0
###
POST {{var}}/sessions HTTP/1.1
Content-Type: application/json

{
   "email" : "hamiltonsilva@gmail.com",
   "password": "massango"
}

###

# Create sesseion for provider 

### 
POST {{var}}/sessions HTTP/1.1
Content-Type: application/json

{
   "email" : "Milton@Silva.com",
   "password": "Massango"
}

