@var = http://localhost:3333

# Create User 

###
POST {{var}}/users HTTP/1.1
Content-Type: application/json

 {
   "name" : "Hamilton Alexandre",
   "email" : "hamiltonsilva@gmail.com",
   "password": "massango"
 }

###

# Update user 

###
PUT http://localhost:3333/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjIzODM0OTUxLCJleHAiOjE2MjQ0Mzk3NTF9.unGLGE0rxUOwjgLEFNX1i5c1C7hTzarJvyIFMxE0TuU

{
  "email" : "hamiltonsilva@gmail.com",
  "provider" : true
}
###