@var = http://localhost:3333

# Create User 

###
POST {{var}}/users HTTP/1.1
Content-Type: application/json

 {
   "name" : "Carlos Alexandre",
   "email" : "carlos@gmail.com",
   "password": "massango"
 }

###

# Update user 

###
PUT http://localhost:3333/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzMzI3NDExLCJleHAiOjE2MjM5MzIyMTF9.SeOmzXEPI7bFUuyICv5_as_Em2f0tMvZoaDCpn_nf6Q

{
  "email" : "carlos@gmail.com",
  "avatar_id" : 1
}
###