@var = http://localhost:3333

# Create User 

###
POST {{var}}/users HTTP/1.1
Content-Type: application/json

 {
   "name" : "Carlos Alexandre",
   "email" : "carlos@gmail.com",
   "password": "massango"
 }

###

# Update user 

###
PUT http://localhost:3333/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjE0MzM0NjgzLCJleHAiOjE2MTQ5Mzk0ODN9.LknhjhNWE8VC1H4vv4Ekl73L5LjL66Nwo_Nnsfv61uQ

{
  "email" : "carlos@gmail.com",
  "avatar_id" : 2
}
###